[package]
name = "winamp_sys"
version = "0.1.0"
authors = ["Suppr(@suppr)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = "0.3"
